add new MC samples

diff --git a/execution b/execution
--- a/execution
+++ b/execution
@@ -2,9 +2,15 @@
 set -e
 
 #=== Preselection ===#
-#time ./fireBatchJobs -p > >(tee log/stdout.log) 2> >(tee log/stderr.log >&2)
-
-#echo "Rename log/stdout.log to log/stdout_pre.log"; mv log/stdout.log log/stdout_pre.log; mv log/stderr.log log/stderr_pre.log
+function Preselection(){
+    time ./fireBatchJobs -p > >(tee log/stdout.log) 2> >(tee log/stderr.log >&2)
+    ./check_submit_status | tee -a log/stdout.log
+}
+function Intermission(){
+    echo "Rename log/stdout.log to log/stdout_pre.log";
+    mv log/stdout.log log/stdout_pre.log
+    mv log/stderr.log log/stderr_pre.log
+}
 
 #=== Selection ===#
 function Selection(){
@@ -12,11 +18,37 @@ function Selection(){
     time ./fireBatchJobs -s ${CHANNEL} > >(tee log/stdout.log) 2> >(tee log/stderr.log >&2)
     sleep 1m; sleep 20s # Depends on the condition of ntugrid5 computers...
     ./check_submit_status | tee -a log/stdout.log
-    #./run_macro_stackPlots ${CHANNEL}
-    #./script/resetPlotsChannels plots_${CHANNEL}
-    #mv log/stdout.log log/stdout_${CHANNEL}.log
-    #mv log/stderr.log log/stderr_${CHANNEL}.log
+}
+function AfterSelection(){
+    CHANNEL=$1
+    ./run_macro_stackPlots ${CHANNEL}
+    ./script/resetPlotsChannels plots_${CHANNEL}
+    cp -p log/stdout.log plots_${CHANNEL}/stdout_${CHANNEL}.log
+    cp -p log/stderr.log plots_${CHANNEL}/stderr_${CHANNEL}.log
+    mv log/stdout.log log/stdout_${CHANNEL}.log
+    mv log/stderr.log log/stderr_${CHANNEL}.log
+}
+function ReRunStackPlotsOnly(){
+    CHANNEL=$1
+    if [ ! -d plots ]; then echo "[INFO] mv plots_${CHANNEL} plots"; mv plots_${CHANNEL} plots;
+    else echo "[WARNNING] dir plots exists! (abort)"; exit 1;
+    fi
+    ./run_macro_stackPlots ${CHANNEL}
+    ./script/resetPlotsChannels plots_${CHANNEL}
+    cp -p log/stdout.log plots_${CHANNEL}/stdout_${CHANNEL}.log
+    cp -p log/stderr.log plots_${CHANNEL}/stderr_${CHANNEL}.log
+    mv log/stdout.log log/stdout_${CHANNEL}.log
+    mv log/stderr.log log/stderr_${CHANNEL}.log
 }
 
+#=== Main Conduction ===#
+#Preselection
+#Intermission
+
 #Selection "hadronic" #selection and make plots for hadronic channel
-Selection "leptonic" #selection and make plots for leptonic channel
+#AfterSelection "hadronic" 
+#Selection "leptonic" #selection and make plots for leptonic channel
+#AfterSelection "leptonic" 
+
+ReRunStackPlotsOnly "hadronic"
+ReRunStackPlotsOnly "leptonic"
